# Generated by Django 3.1 on 2020-08-24 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200824_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyaddress',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='propertyreview',
            old_name='address_id',
            new_name='propertyAddress',
        ),
        migrations.RenameField(
            model_name='propertyreview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='propertyreview',
            unique_together={('propertyAddress', 'user')},
        ),
    ]
