# Generated by Django 3.1 on 2020-08-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200825_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyReview',
        ),
    ]
