# Generated by Django 3.1 on 2020-08-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(max_length=100, null=True, verbose_name='address 2'),
        ),
    ]
