# Generated by Django 3.1 on 2020-08-30 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200826_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='rating')),
                ('reviewedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewedUser', to=settings.AUTH_USER_MODEL)),
                ('reviewingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewingUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reviewingUser', 'reviewedUser')},
            },
        ),
    ]
